### PR TITLE
Add AUTh schools

### LINKED ISSUE #117: Add AUTh schools
I think I can do it

If I understand correctly, I have to add the entries in _/backend/data.json_, and update _/frontend/public/faq/index.html_, right? Is there anything else?

### PR DESCRIPTION
**Pull request by anestv**
Closes #117

### CODE REVIEW

**Review by dimkarakostas — APPROVED** [review]
Looks good. Out of curiosity, how did you come up with the regexes? ( If you want to answer offline, email me ;) )

**Comment by anestv** [comment]
I went to https://www.auth.gr/search/people and put a common name and the department I want.

I think the way the emails in AUTh work is that you select a username when you create your account, and your mail is username@department.auth.gr. But it seems that any mails sent to username@auth.gr will also be delivered normally.

**Comment by dimkarakostas** [comment]
Oh very nice, good job!

**Comment by dimkarakostas** [comment]
If you could also share it with anyone you might know at auth or with any fb groups it would be perfect :)

**Comment by anestv** [comment]
ok :smiley:

**Pull request merged**
